### ISSUE TITLE
not getting output

### ISSUE THREAD

**Issue by kshireesha** [KhyatiMehta3/CymbelineInnovation_RemoteLabs#1]
after typing the ip address in the new webpage we are getting as THIS SITE CANNOT BE REACHED

**Comment by kkmehta03** [comment]
Please make sure your WEMOS is on the same network as the device you attempt to access it with.
If this is already true, then there are 2 possible reasons. 
1. Your WEMOS device isn't connected to your specified WiFi network. To find out if this is the problem, please open your serial monitor (on the top right corner of the Arduino IDE) and press reset button on your device. If you get continuous dots like this - ".................." Then it means that the WEMOS isn't connected to your Wifi. In this case, crosscheck your SSID spelling (remember, SSIDs and passwords are case sensitive).
2. The IP address you may have given to your WEMOS is occupied by some other device. 
In the setup part of the code, change your IP Address for the device to (192,168,43, <some number>);
and keep your Gateway as it is. If you still don't get the output, change your gateway to (192,168,43,1);

If you still have issues, please mention them in detail along with screenshots so handling them is easier.

**Comment by kshireesha** [comment]
We got the output....thank you mam....
