### ISSUE TITLE
not getting output 

### ISSUE THREAD

**Issue by kshireesha** [KhyatiMehta3/CymbelineInnovation_RemoteLabs#2]
first time we got the output but again we are trying by changing the ip address but again it is showing as THIS SITE CANNOT BE REACHED

**Comment by Prasannakamath** [comment]
First change the hotspot to which your iot board is connected. Then use the new IP address assigned to it. You cannot directly change the IP address of your device.

**Comment by kkmehta03** [comment]
@kshireesha , Can you elaborate on your issue? What IP address have you changed?

**Comment by kshireesha** [comment]
We got the output and thank you for your reply
